const List<String> kGemClasses = [
  'Aman',
  'Ruby',
  'Sapphire',
  'Emerald',
  'Topaz',
  'Opal',
  'Pearl',
];

const List<String> kClasses = [
  'Year 1 Aman',
  'Year 1 Ruby',
  'Year 1 Sapphire',
  'Year 1 Emerald',
  'Year 1 Topaz',
  'Year 1 Opal',
  'Year 1 Pearl',
  'Year 2 Aman',
  'Year 2 Ruby',
  'Year 2 Sapphire',
  'Year 2 Emerald',
  'Year 2 Topaz',
  'Year 2 Opal',
  'Year 2 Pearl',
  'Year 3 Aman',
  'Year 3 Ruby',
  'Year 3 Sapphire',
  'Year 3 Emerald',
  'Year 3 Topaz',
  'Year 3 Opal',
  'Year 3 Pearl',
  'Year 4 Aman',
  'Year 4 Ruby',
  'Year 4 Sapphire',
  'Year 4 Emerald',
  'Year 4 Topaz',
  'Year 4 Opal',
  'Year 4 Pearl',
  'Year 5 Aman',
  'Year 5 Ruby',
  'Year 5 Sapphire',
  'Year 5 Emerald',
  'Year 5 Topaz',
  'Year 5 Opal',
  'Year 5 Pearl',
  'Year 6 Aman',
  'Year 6 Ruby',
  'Year 6 Sapphire',
  'Year 6 Emerald',
  'Year 6 Topaz',
  'Year 6 Opal',
  'Year 6 Pearl',
];

// For annual update — maps each class to the next year's equivalent
const Map<String, String> kPromotionMap = {
  'Year 1 Aman': 'Year 2 Aman', 'Year 1 Ruby': 'Year 2 Ruby',
  'Year 1 Sapphire': 'Year 2 Sapphire', 'Year 1 Emerald': 'Year 2 Emerald',
  'Year 1 Topaz': 'Year 2 Topaz', 'Year 1 Opal': 'Year 2 Opal',
  'Year 1 Pearl': 'Year 2 Pearl',

  'Year 2 Aman': 'Year 3 Aman', 'Year 2 Ruby': 'Year 3 Ruby',
  'Year 2 Sapphire': 'Year 3 Sapphire', 'Year 2 Emerald': 'Year 3 Emerald',
  'Year 2 Topaz': 'Year 3 Topaz', 'Year 2 Opal': 'Year 3 Opal',
  'Year 2 Pearl': 'Year 3 Pearl',

  'Year 3 Aman': 'Year 4 Aman', 'Year 3 Ruby': 'Year 4 Ruby',
  'Year 3 Sapphire': 'Year 4 Sapphire', 'Year 3 Emerald': 'Year 4 Emerald',
  'Year 3 Topaz': 'Year 4 Topaz', 'Year 3 Opal': 'Year 4 Opal',
  'Year 3 Pearl': 'Year 4 Pearl',

  'Year 4 Aman': 'Year 5 Aman', 'Year 4 Ruby': 'Year 5 Ruby',
  'Year 4 Sapphire': 'Year 5 Sapphire', 'Year 4 Emerald': 'Year 5 Emerald',
  'Year 4 Topaz': 'Year 5 Topaz', 'Year 4 Opal': 'Year 5 Opal',
  'Year 4 Pearl': 'Year 5 Pearl',

  'Year 5 Aman': 'Year 6 Aman', 'Year 5 Ruby': 'Year 6 Ruby',
  'Year 5 Sapphire': 'Year 6 Sapphire', 'Year 5 Emerald': 'Year 6 Emerald',
  'Year 5 Topaz': 'Year 6 Topaz', 'Year 5 Opal': 'Year 6 Opal',
  'Year 5 Pearl': 'Year 6 Pearl',
  // Year 6 graduates — not mapped, so they won't be promoted
};
