// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjzYXYzfbk9lGjbiKfqkiTshtZqISB_qA',
    appId: '1:890120499254:web:bfc8996dbcc5d6ea47e897',
    messagingSenderId: '890120499254',
    projectId: 'sriwaap-158cd',
    authDomain: 'sriwaap-158cd.firebaseapp.com',
    storageBucket: 'sriwaap-158cd.firebasestorage.app',
    measurementId: 'G-YYRJ1QDNFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-L186U_MJR7I-RcLIVkV6ip-F6RLuFDQ',
    appId: '1:890120499254:android:356cf7f034707ff747e897',
    messagingSenderId: '890120499254',
    projectId: 'sriwaap-158cd',
    storageBucket: 'sriwaap-158cd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjzYXYzfbk9lGjbiKfqkiTshtZqISB_qA',
    appId: '1:890120499254:web:d26a3797c5fa688447e897',
    messagingSenderId: '890120499254',
    projectId: 'sriwaap-158cd',
    authDomain: 'sriwaap-158cd.firebaseapp.com',
    storageBucket: 'sriwaap-158cd.firebasestorage.app',
    measurementId: 'G-THPXZF8PN6',
  );
}
